### PR TITLE
Update the ExAws dependency so that it no longer locks to 2.0

### PR DESCRIPTION
**Pull request by marramgrass**
We've bumped into issues using both https://github.com/brianlow/ex_aws_transcribe and this KMS plugin in the same installation, as the transcribe plugin needs ExAws 2.1.x.

This pull request updates the dependency on ExAws to 2.1.x. I have tested it as working.

### CODE REVIEW

**Comment by bmuller** [comment]
@benwilson512 Thanks for all your work on this lib!  This PR seems like a quick and easy one to review... any chance we could get this merged and #3 closed?

**Comment by bmuller** [comment]
Thanks for merging @benwilson512!  Since the last release was in _2017_ - any chance of including this merge in a new release?

Thanks again for the lib!

**Comment by benwilson512** [comment]
Do note https://github.com/ex-aws/ex_aws_kms/issues/1.

**Comment by hirocaster** [comment]
Thanks @bmuller .
I could not chek this PR until now.

**Pull request merged**
